export const CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT";
export const REMOVE_USER_GROUP_CHAT = "REMOVE_USER_GROUP_CHAT";
export const UPDATE_GROUP_NAME = "UPDATE_GROUP_NAME";
export const ADD_USERS_GROUP = "ADD_USERS_GROUP";
export const ADD_USERS_SINGLE = "ADD_USERS_SINGLE";
export const LEAVE_GROUP_CHAT = "LEAVE_GROUP_CHAT";
export const DELETE_GROUP_CHAT = "DELETE_GROUP_CHAT";
